import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getFirestore, doc, onSnapshot, setDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';
import { getAuth, GoogleAuthProvider, signInWithPopup, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';

const firebaseConfig={apiKey:'AIzaSyDewRQDycXHbFZFtbrb78_wmPbp4jfIggk',authDomain:'eat-play-cheers.firebaseapp.com',projectId:'eat-play-cheers',storageBucket:'eat-play-cheers.firebasestorage.app',messagingSenderId:'199775195780',appId:'1:199775195780:web:d815293a973a122c73e8d1'};
const firebaseApp=initializeApp(firebaseConfig);
const db=getFirestore(firebaseApp);
const auth=getAuth(firebaseApp);
const provider=new GoogleAuthProvider();
const tripDoc=doc(db,'trips','eat-play-cheers');
let currentUser=null;
let remoteReady=false;
let saveTimer=null;
let suppressRemoteSave=false;

const STORAGE_KEY='dues-manager-v1';
const won=new Intl.NumberFormat('ko-KR',{style:'currency',currency:'KRW',maximumFractionDigits:0});
const today=new Date().toISOString().slice(0,10);
const $=(id)=>document.getElementById(id);
const MEMBER_NAMES=['고현정','권오근','길한','나효진','윤지원','이재훈','이진아','이해진','함형주','홍석일'];
const TRIP_START='2026-07-25';
const TRIP_END='2026-07-26';
const DEFAULT_DUE=150000;
let state=loadState();
function uid(){return crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random());}
function defaultState(){return{meetingName:'Eat,Play,Cheers',defaultDue:DEFAULT_DUE,tripStart:TRIP_START,tripEnd:TRIP_END,members:MEMBER_NAMES.map((name,index)=>({id:'member-'+(index+1),name,contact:'',due:DEFAULT_DUE,status:'active'})),transactions:[]};}
function normalizeState(data){
  data.meetingName='Eat,Play,Cheers';
  data.defaultDue=DEFAULT_DUE;
  data.tripStart=TRIP_START;
  data.tripEnd=TRIP_END;
  const names=(data.members||[]).map(m=>m.name);
  if(names.join('|')!==MEMBER_NAMES.join('|')) data.members=MEMBER_NAMES.map((name,index)=>({id:'member-'+(index+1),name,contact:'',due:DEFAULT_DUE,status:'active'}));
  data.members=data.members.map((member,index)=>({id:member.id||'member-'+(index+1),name:member.name,contact:member.contact||'',due:DEFAULT_DUE,status:member.status||'active'}));
  data.transactions=data.transactions||[];
  return data;
}
function loadState(){try{const saved=localStorage.getItem(STORAGE_KEY);return normalizeState(saved?JSON.parse(saved):defaultState());}catch{return defaultState();}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));if(!suppressRemoteSave)scheduleRemoteSave();}
function canEdit(){return !!currentUser;}
function scheduleRemoteSave(){if(!canEdit())return;clearTimeout(saveTimer);saveTimer=setTimeout(pushRemoteState,250);}
async function pushRemoteState(){if(!canEdit())return;try{await setDoc(tripDoc,{state:normalizeState(structuredClone(state)),updatedAt:serverTimestamp(),updatedBy:currentUser.email||currentUser.uid},{merge:true});setSyncStatus('저장됨');}catch(error){console.error(error);setSyncStatus('저장 실패');alert('저장 권한이 없거나 연결에 실패했습니다.');}}
function setSyncStatus(text){const el=$('syncStatus');if(el)el.textContent=text;}
function applyRemoteState(next){suppressRemoteSave=true;state=normalizeState(next);localStorage.setItem(STORAGE_KEY,JSON.stringify(state));render();suppressRemoteSave=false;}
function startRemoteSync(){onSnapshot(tripDoc,(snap)=>{remoteReady=true;if(snap.exists()&&snap.data().state){applyRemoteState(snap.data().state);setSyncStatus('최신 데이터');}else{setSyncStatus(canEdit()?'관리자 저장 대기':'보기 전용');if(canEdit())pushRemoteState();}},(error)=>{console.error(error);setSyncStatus('연결 실패');});}
function updateAuthUI(){document.body.classList.toggle('viewer-mode',!canEdit());const login=$('adminLogin');const logout=$('adminLogout');if(login)login.classList.toggle('is-hidden',canEdit());if(logout)logout.classList.toggle('is-hidden',!canEdit());setSyncStatus(canEdit()?'관리자 모드':'보기 전용');}
async function loginAdmin(){try{await signInWithPopup(auth,provider);}catch(error){console.error(error);alert('로그인에 실패했습니다. 팝업 차단 여부를 확인해주세요.');}}
async function logoutAdmin(){await signOut(auth);}
function fmt(v){return won.format(Number(v||0));}
function comma(v){return new Intl.NumberFormat('ko-KR').format(Number(v||0));}
function parseMoney(v){return Number(String(v||'').replace(/[^0-9]/g,''));}
function fmtImage(v){return comma(v)+'원';}
function bindMoneyInput(el){el.addEventListener('input',()=>{const raw=parseMoney(el.value);el.value=raw?comma(raw):'';});}
function activeMembers(){return state.members.filter(m=>m.status==='active');}
function due(m){return Number(m.due||state.defaultDue||0);}
function mname(id){return (state.members.find(m=>m.id===id)||{}).name||'여행 공금';}
function inTrip(tx){const d=tx.date||'';return d>=state.tripStart&&d<=state.tripEnd;}
function splitAmount(amount,count){if(!count||amount<=0)return{perPerson:0,remainder:0};return{perPerson:Math.floor(amount/count),remainder:amount%count};}
function init(){
$('meetingNameDisplay').textContent=state.meetingName;$('tripDateDisplay').textContent='7/25 ~ 26';$('defaultDueDisplay').textContent=comma(state.defaultDue)+'원';$('paymentDate').value=today;$('expenseDate').value=today;$('paymentAmount').value=comma(state.defaultDue);bindMoneyInput($('paymentAmount'));bindMoneyInput($('expenseAmount'));bindMoneyInput($('memberDue'));
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));
$('adminLogin').addEventListener('click',loginAdmin);$('adminLogout').addEventListener('click',logoutAdmin);$('paymentMember').addEventListener('change',fillPaymentAmount);$('paymentForm').addEventListener('submit',addPayment);$('expenseForm').addEventListener('submit',addExpense);$('memberForm').addEventListener('submit',addMember);
onAuthStateChanged(auth,(user)=>{currentUser=user;updateAuthUI();if(user&&remoteReady)pushRemoteState();});startRemoteSync();updateAuthUI();$('searchInput').addEventListener('input',renderLedger);$('typeFilter').addEventListener('change',renderLedger);$('markMonthPaid').addEventListener('click',markAllPaid);$('copySummary').addEventListener('click',copySummary);$('exportPaymentImage').addEventListener('click',exportPaymentStatusImage);$('exportSummaryImage').addEventListener('click',exportSummaryImage);$('exportBtn').addEventListener('click',exportData);$('importFile').addEventListener('change',importData);$('resetBtn').addEventListener('click',resetAll);render();}
function switchTab(name){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('is-active',b.dataset.tab===name));document.querySelectorAll('.entry-form').forEach(f=>f.classList.toggle('is-hidden',f.dataset.panel!==name));}
function addPayment(e){e.preventDefault();if(!canEdit())return alert('관리자만 입력할 수 있습니다.');const memberId=$('paymentMember').value;if(!memberId)return;state.transactions.unshift({id:uid(),type:'payment',memberId,title:'여행 회비 납부',amount:parseMoney($('paymentAmount').value),date:$('paymentDate').value||today,memo:$('paymentMemo').value.trim()});$('paymentMemo').value='';save();render();}
function addExpense(e){e.preventDefault();if(!canEdit())return alert('관리자만 입력할 수 있습니다.');state.transactions.unshift({id:uid(),type:'expense',memberId:$('expensePayer').value,title:$('expenseTitle').value.trim(),amount:parseMoney($('expenseAmount').value),date:$('expenseDate').value||today,memo:'지출'});e.target.reset();$('expenseDate').value=today;save();render();}
function addMember(e){e.preventDefault();if(!canEdit())return alert('관리자만 입력할 수 있습니다.');state.members.push({id:uid(),name:$('memberName').value.trim(),contact:$('memberContact').value.trim(),due:parseMoney($('memberDue').value)||state.defaultDue,status:$('memberStatus').value});e.target.reset();$('memberStatus').value='active';save();render();}
function markAllPaid(){if(!canEdit())return alert('관리자만 입력할 수 있습니다.');const paid=new Set(state.transactions.filter(tx=>tx.type==='payment').map(tx=>tx.memberId));activeMembers().forEach(m=>{if(!paid.has(m.id))state.transactions.unshift({id:uid(),type:'payment',memberId:m.id,title:'여행 회비 납부',amount:due(m),date:state.tripStart,memo:'전체 납부 처리'});});save();render();}
function totals(){const tripTx=state.transactions;const income=tripTx.filter(tx=>tx.type==='payment').reduce((s,tx)=>s+Number(tx.amount),0);const expense=tripTx.filter(tx=>tx.type==='expense').reduce((s,tx)=>s+Number(tx.amount),0);const balance=income-expense;const count=activeMembers().length;const shortage=balance<0?Math.abs(balance):0;const surplus=balance>0?balance:0;return{tripTx,income,expense,balance,count,shortage,surplus,shortSplit:splitAmount(shortage,count),surplusSplit:splitAmount(surplus,count)};}
function render(){ $('pageTitle').textContent=state.meetingName||'Eat,Play,Cheers'; $('tripRange').textContent='7/25 ~ 26'; $('meetingNameDisplay').textContent=state.meetingName; $('tripDateDisplay').textContent='7/25 ~ 26'; $('defaultDueDisplay').textContent=comma(state.defaultDue)+'원'; renderSelects(); renderMetrics(); renderLedger(); renderMembers(); renderSettlement(); }
function renderSelects(){const options=state.members.map(m=>'<option value="'+m.id+'">'+esc(m.name)+'</option>').join('');$('paymentMember').innerHTML=options;$('expensePayer').innerHTML='<option value="">여행 공금</option>'+options;fillPaymentAmount();}
function fillPaymentAmount(){const m=state.members.find(x=>x.id===$('paymentMember').value);if(m)$('paymentAmount').value=comma(due(m));}
function renderMetrics(){const t=totals();const paid=new Set(t.tripTx.filter(tx=>tx.type==='payment').map(tx=>tx.memberId));const unpaid=activeMembers().filter(m=>!paid.has(m.id)).reduce((s,m)=>s+due(m),0);$('balanceMetric').textContent=fmt(t.balance);$('incomeMetric').textContent=fmt(t.income);$('expenseMetric').textContent=fmt(t.expense);$('unpaidMetric').textContent=fmt(unpaid);$('adjustMetric').textContent=t.shortage?('추가 '+fmt(t.shortSplit.perPerson)+'/인'):t.surplus?('환급 '+fmt(t.surplusSplit.perPerson)+'/인'):'정산 없음';}
function renderLedger(){const query=$('searchInput').value.trim().toLowerCase();const filter=$('typeFilter').value;const list=state.transactions.filter(tx=>{const hay=[tx.title,tx.memo,mname(tx.memberId),tx.date].join(' ').toLowerCase();return(filter==='all'||tx.type===filter)&&hay.includes(query);});$('ledgerList').innerHTML=list.length?list.map(tx=>'<article class="ledger-item"><div class="ledger-main"><div><div class="ledger-title">'+esc(tx.title)+'</div><div class="meta">'+tx.date+' · '+esc(mname(tx.memberId))+(tx.memo?' · '+esc(tx.memo):'')+'</div></div><div class="amount '+(tx.type==='payment'?'income':'expense')+'">'+(tx.type==='payment'?'+':'-')+fmt(tx.amount)+'</div></div><div class="row-actions"><button class="small-btn" type="button" onclick="deleteTransaction(\''+tx.id+'\')">삭제</button></div></article>').join(''):'<div class="empty-state">아직 기록이 없습니다.</div>';}
function renderMembers(){const tripPayments=state.transactions.filter(tx=>tx.type==='payment');const paidMap=new Map();tripPayments.forEach(tx=>paidMap.set(tx.memberId,(paidMap.get(tx.memberId)||0)+Number(tx.amount)));const rows=state.members.map(m=>{const need=due(m);const paid=paidMap.get(m.id)||0;const ratio=need?Math.min(100,Math.round(paid/need*100)):100;const ok=m.status!=='active'||paid>=need;return{member:m,need,paid,ratio,ok};}).sort((a,b)=>{if(a.ok!==b.ok)return a.ok?1:-1;if(b.paid!==a.paid)return b.paid-a.paid;return a.member.name.localeCompare(b.member.name,'ko');});$('memberList').innerHTML=rows.length?rows.map(row=>{const m=row.member;return '<article class="member-item"><div class="member-main"><div><div class="member-name">'+esc(m.name)+'</div><div class="meta">'+(m.contact?esc(m.contact)+' · ':'')+(m.status==='active'?'참가':'불참')+' · 납부 '+fmt(row.paid)+' / '+fmt(row.need)+'</div></div><span class="status-pill '+(row.ok?'paid':'unpaid')+'">'+(row.ok?'완료':'미납')+'</span></div><div class="progress-track"><div class="progress-fill" style="width:'+row.ratio+'%"></div></div><div class="row-actions"><button class="small-btn" type="button" onclick="toggleMember(\''+m.id+'\')">상태 변경</button><button class="small-btn" type="button" onclick="deleteMember(\''+m.id+'\')">삭제</button></div></article>';}).join(''):'<div class="empty-state">아직 회원이 없습니다.</div>';}
function renderSettlement(){const t=totals();const paid=new Set(t.tripTx.filter(tx=>tx.type==='payment').map(tx=>tx.memberId));const unpaid=activeMembers().filter(m=>!paid.has(m.id));let adjust='정산 없음';if(t.shortage)adjust='지출이 수입보다 '+fmt(t.shortage)+' 많습니다. 참가자 '+t.count+'명 기준 1인당 추가 '+fmt(t.shortSplit.perPerson)+' 납부'+(t.shortSplit.remainder?' + 자투리 '+fmt(t.shortSplit.remainder):'');if(t.surplus)adjust='수입이 지출보다 '+fmt(t.surplus)+' 많습니다. 참가자 '+t.count+'명 기준 1인당 '+fmt(t.surplusSplit.perPerson)+' 환급'+(t.surplusSplit.remainder?' + 남는 자투리 '+fmt(t.surplusSplit.remainder):'');$('settlementText').value='['+state.meetingName+' 여행 회비 정산]\n여행일자: '+state.tripStart+' ~ '+state.tripEnd+'\n참가 회비: 1인 '+fmt(state.defaultDue)+'\n회비 수입: '+fmt(t.income)+'\n여행 지출: '+fmt(t.expense)+'\n현재 잔액: '+fmt(t.balance)+'\n미납: '+(unpaid.length?unpaid.map(m=>m.name+' '+fmt(due(m))).join(', '):'없음')+'\n정산 제안: '+adjust;}

function canvasBase(width,height){const canvas=document.createElement('canvas');const scale=2;canvas.width=width*scale;canvas.height=height*scale;const ctx=canvas.getContext('2d');ctx.scale(scale,scale);ctx.fillStyle='#ffffff';ctx.fillRect(0,0,width,height);ctx.textBaseline='alphabetic';ctx.lineWidth=1;return{canvas,ctx,width,height};}
function drawText(ctx,text,x,y,size,color='#182334',weight='700',align='left'){ctx.fillStyle=color;ctx.font=weight+' '+size+'px Arial, Malgun Gothic, sans-serif';ctx.textAlign=align;ctx.fillText(text,x,y);}
function drawPill(ctx,text,x,y,w,color,bg){ctx.fillStyle=bg;roundRect(ctx,x,y,w,28,14);ctx.fill();drawText(ctx,text,x+w/2,y+19,13,color,'800','center');}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath();}
function downloadCanvas(canvas,name){const a=document.createElement('a');a.download=name;a.href=canvas.toDataURL('image/png');a.click();}
function paymentRows(){const paidMap=new Map();state.transactions.filter(tx=>tx.type==='payment').forEach(tx=>paidMap.set(tx.memberId,(paidMap.get(tx.memberId)||0)+Number(tx.amount)));return state.members.map(member=>{const paid=paidMap.get(member.id)||0;const need=due(member);return{name:member.name,status:member.status,paid,need,done:member.status!=='active'||paid>=need};});}
function exportPaymentStatusImage(){const rows=paymentRows();const width=900;const rowH=58;const tableTop=206;const height=250+rows.length*rowH;const c=canvasBase(width,height);const ctx=c.ctx;const left=54;const right=width-54;const paidX=right-260;const statusX=right-70;drawText(ctx,'Eat,Play,Cheers',left,62,30,'#1e40af','900');drawText(ctx,'회비 납부 현황',left,100,22,'#182334','900');drawText(ctx,'여행일자 7/25 ~ 26 · 기준 회비 '+fmtImage(state.defaultDue),left,132,16,'#627086','700');ctx.strokeStyle='#d7e1ef';ctx.beginPath();ctx.moveTo(left,160);ctx.lineTo(right,160);ctx.stroke();drawText(ctx,'이름',left+12,tableTop,14,'#627086','800');drawText(ctx,'납부액',paidX,tableTop,14,'#627086','800');drawText(ctx,'상태',statusX,tableTop,14,'#627086','800','center');ctx.strokeStyle='#edf2f7';ctx.beginPath();ctx.moveTo(left,tableTop+18);ctx.lineTo(right,tableTop+18);ctx.stroke();rows.forEach((row,i)=>{const y=tableTop+58+i*rowH;ctx.fillStyle=i%2?'#f8fbff':'#ffffff';ctx.fillRect(left,y-34,right-left,rowH);drawText(ctx,row.name,left+12,y,17,'#182334','900');drawText(ctx,fmtImage(row.paid),paidX,y,16,row.done?'#1e40af':'#dc5b52','900');drawPill(ctx,row.done?'완납':'미납',statusX-36,y-24,72,row.done?'#1e40af':'#dc5b52',row.done?'#dbeafe':'#fee2e2');});drawText(ctx,'생성일 '+new Date().toLocaleDateString('ko-KR'),left,height-28,12,'#94a3b8','700','left');downloadCanvas(c.canvas,'eat-play-cheers-payment-status.png');}
function exportSummaryImage(){const t=totals();const paid=new Set(state.transactions.filter(tx=>tx.type==='payment').map(tx=>tx.memberId));const unpaid=activeMembers().filter(m=>!paid.has(m.id));const width=900;const height=620;const c=canvasBase(width,height);const ctx=c.ctx;drawText(ctx,'Eat,Play,Cheers',48,64,30,'#1e40af','900');drawText(ctx,'현재 회비 현황',48,102,22,'#182334','900');drawText(ctx,'여행일자 7/25 ~ 26',48,134,16,'#627086','700');const cards=[['회비 수입',fmt(t.income),'#1e40af'],['여행 지출',fmt(t.expense),'#dc5b52'],['현재 잔액',fmt(t.balance),t.balance>=0?'#0f8aa8':'#dc5b52'],['미납 회비',fmt(unpaid.reduce((s,m)=>s+due(m),0)),'#b45309']];cards.forEach((card,i)=>{const x=48+(i%2)*402;const y=178+Math.floor(i/2)*130;ctx.fillStyle='#f8fbff';roundRect(ctx,x,y,360,96,18);ctx.fill();ctx.strokeStyle='#d7e1ef';ctx.stroke();drawText(ctx,card[0],x+24,y+34,15,'#627086','800');drawText(ctx,card[1],x+24,y+72,26,card[2],'900');});let adjust='정산 없음';let color='#1e40af';if(t.shortage){adjust='1인당 추가 납부 '+fmt(t.shortSplit.perPerson)+(t.shortSplit.remainder?' · 자투리 '+fmt(t.shortSplit.remainder):'');color='#dc5b52';}else if(t.surplus){adjust='1인당 환급 '+fmt(t.surplusSplit.perPerson)+(t.surplusSplit.remainder?' · 자투리 '+fmt(t.surplusSplit.remainder):'');color='#0f8aa8';}ctx.fillStyle='#eef5ff';roundRect(ctx,48,454,width-96,94,18);ctx.fill();drawText(ctx,'정산 제안',72,492,16,'#627086','900');drawText(ctx,adjust,72,530,24,color,'900');drawText(ctx,'참가자 '+activeMembers().length+'명 기준 · 첫 회비 '+fmtImage(state.defaultDue),48,584,14,'#627086','800');drawText(ctx,'생성일 '+new Date().toLocaleDateString('ko-KR'),width-48,584,12,'#94a3b8','700','right');downloadCanvas(c.canvas,'eat-play-cheers-summary.png');}

window.deleteTransaction=function(id){if(!canEdit())return alert('관리자만 수정할 수 있습니다.');state.transactions=state.transactions.filter(tx=>tx.id!==id);save();render();};
window.toggleMember=function(id){if(!canEdit())return alert('관리자만 수정할 수 있습니다.');const m=state.members.find(x=>x.id===id);if(!m)return;m.status=m.status==='active'?'paused':'active';save();render();};
window.deleteMember=function(id){if(!canEdit())return alert('관리자만 수정할 수 있습니다.');if(!confirm('이 회원을 삭제할까요? 관련 거래 내역은 남아 있습니다.'))return;state.members=state.members.filter(m=>m.id!==id);save();render();};
async function copySummary(){await navigator.clipboard.writeText($('settlementText').value);$('copySummary').textContent='복사됨';setTimeout(()=>$('copySummary').textContent='복사',1200);}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=(state.meetingName||'trip')+'-dues.json';a.click();URL.revokeObjectURL(url);}
function importData(e){if(!canEdit())return alert('관리자만 가져올 수 있습니다.');const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{state=normalizeState(JSON.parse(reader.result));save();render();}catch{alert('가져올 수 없는 파일입니다.');}};reader.readAsText(file);e.target.value='';}
function resetAll(){if(!canEdit())return alert('관리자만 초기화할 수 있습니다.');if(!confirm('모든 회비 데이터를 초기화할까요?'))return;state=defaultState();save();render();}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
init();